
project_id = "zjiuajfoimfmavezpmob"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://zjiuajfoimfmavezpmob.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[edge_functions]
enabled = true

[[edge_functions.function]]
name = "sync-insurance-data"

[[edge_functions.function]]
name = "medical-ai-assistant"

[[edge_functions.function]]
name = "ai-health-chat"

[functions.ai-health-chat]
verify_jwt = false
