
-- Insert comprehensive Nigerian medications (Part 2 of 5)
INSERT INTO public.medications (
  name, category, price, description, brand, pack_size, prescription_required, 
  in_stock, rating, active_ingredient, dosage, manufacturer, therapeutic_class, 
  indication, generic_name, strength, route_of_administration, warnings
) VALUES

-- Respiratory Medications
('Salbutamol Inhaler', 'Respiratory', 4800, 'Quick-relief bronchodilator', 'GSK', '1 inhaler', true, true, 4.8, 'Salbutamol', '100mcg/dose', 'GSK Nigeria', 'Beta2 Agonist', 'Asthma, COPD', 'Albuterol', '100mcg/dose', 'Inhalation', ARRAY['Rinse mouth after use']),
('Beclomethasone Inhaler', 'Respiratory', 6500, 'Inhaled corticosteroid', 'Teva', '1 inhaler', true, true, 4.6, 'Beclomethasone', '250mcg/dose', 'Teva Nigeria', 'Inhaled Corticosteroid', 'Asthma prevention', 'Beclomethasone', '250mcg/dose', 'Inhalation', ARRAY['Use spacer device']),
('Montelukast', 'Respiratory', 5800, 'Leukotriene receptor antagonist', 'Merck', '28 tablets', true, true, 4.5, 'Montelukast', '10mg', 'Merck Nigeria', 'Leukotriene Antagonist', 'Asthma, allergic rhinitis', 'Montelukast', '10mg', 'Oral', ARRAY['Take in evening']),
('Prednisolone', 'Respiratory', 2500, 'Oral corticosteroid', 'GSK', '30 tablets', true, true, 4.4, 'Prednisolone', '5mg', 'GSK Nigeria', 'Corticosteroid', 'Severe asthma, inflammation', 'Prednisolone', '5mg', 'Oral', ARRAY['Taper dose gradually']),
('Theophylline', 'Respiratory', 3200, 'Bronchodilator and anti-inflammatory', 'Abbott', '30 tablets', true, true, 4.2, 'Theophylline', '200mg', 'Abbott Nigeria', 'Methylxanthine', 'Asthma, COPD', 'Theophylline', '200mg', 'Oral', ARRAY['Monitor blood levels']),
('Ipratropium Inhaler', 'Respiratory', 5500, 'Anticholinergic bronchodilator', 'Boehringer Ingelheim', '1 inhaler', true, true, 4.3, 'Ipratropium Bromide', '20mcg/dose', 'Boehringer Ingelheim', 'Anticholinergic', 'COPD', 'Ipratropium', '20mcg/dose', 'Inhalation', ARRAY['Avoid eye contact']),
('Budesonide Inhaler', 'Respiratory', 7200, 'Inhaled corticosteroid', 'AstraZeneca', '1 inhaler', true, true, 4.7, 'Budesonide', '200mcg/dose', 'AstraZeneca', 'Inhaled Corticosteroid', 'Asthma maintenance', 'Budesonide', '200mcg/dose', 'Inhalation', ARRAY['Regular use required']),
('Dextromethorphan Syrup', 'Respiratory', 2800, 'Cough suppressant', 'Pfizer', '120ml', false, true, 4.0, 'Dextromethorphan', '15mg/5ml', 'Pfizer Nigeria', 'Antitussive', 'Dry cough', 'Dextromethorphan', '3mg/ml', 'Oral', ARRAY['Do not exceed recommended dose']),
('Guaifenesin', 'Respiratory', 3200, 'Expectorant', 'Reckitt Benckiser', '100ml', false, true, 4.1, 'Guaifenesin', '100mg/5ml', 'Reckitt Benckiser', 'Expectorant', 'Productive cough', 'Guaifenesin', '20mg/ml', 'Oral', ARRAY['Increase fluid intake']),
('Loratadine', 'Respiratory', 2500, 'Non-sedating antihistamine', 'Schering-Plough', '10 tablets', false, true, 4.3, 'Loratadine', '10mg', 'Schering-Plough', 'Antihistamine', 'Allergic rhinitis', 'Loratadine', '10mg', 'Oral', ARRAY['Once daily dosing']),

-- Gastrointestinal Medications
('Omeprazole', 'Gastrointestinal', 3800, 'Proton pump inhibitor', 'AstraZeneca', '28 capsules', false, true, 4.6, 'Omeprazole', '20mg', 'AstraZeneca Nigeria', 'PPI', 'GERD, peptic ulcers', 'Omeprazole', '20mg', 'Oral', ARRAY['Take before breakfast']),
('Pantoprazole', 'Gastrointestinal', 4200, 'Proton pump inhibitor', 'Nycomed', '28 tablets', false, true, 4.5, 'Pantoprazole', '40mg', 'Nycomed Nigeria', 'PPI', 'GERD, Zollinger-Ellison', 'Pantoprazole', '40mg', 'Oral', ARRAY['Swallow whole']),
('Ranitidine', 'Gastrointestinal', 2500, 'H2 receptor antagonist', 'GSK', '30 tablets', false, true, 4.3, 'Ranitidine', '150mg', 'GSK Nigeria', 'H2 Antagonist', 'Peptic ulcers, GERD', 'Ranitidine', '150mg', 'Oral', ARRAY['Take with or after food']),
('Loperamide', 'Gastrointestinal', 1800, 'Anti-diarrheal', 'Johnson & Johnson', '12 capsules', false, true, 4.4, 'Loperamide HCl', '2mg', 'Johnson & Johnson Nigeria', 'Antidiarrheal', 'Acute diarrhea', 'Loperamide', '2mg', 'Oral', ARRAY['Do not use for bloody diarrhea']),
('Oral Rehydration Salts', 'Gastrointestinal', 850, 'Electrolyte replacement', 'WHO', '10 sachets', false, true, 4.7, 'Sodium Chloride, Glucose', 'Various', 'WHO/UNICEF', 'Electrolyte Replacement', 'Dehydration', 'ORS', 'Various', 'Oral', ARRAY['Prepare fresh solution']),
('Metoclopramide', 'Gastrointestinal', 2200, 'Antiemetic and prokinetic', 'Sanofi', '30 tablets', true, true, 4.2, 'Metoclopramide', '10mg', 'Sanofi Nigeria', 'Dopamine Antagonist', 'Nausea, vomiting', 'Metoclopramide', '10mg', 'Oral', ARRAY['Tardive dyskinesia risk']),
('Simethicone', 'Gastrointestinal', 1500, 'Anti-flatulent', 'Pfizer', '30 tablets', false, true, 4.1, 'Simethicone', '40mg', 'Pfizer Nigeria', 'Anti-flatulent', 'Gas, bloating', 'Simethicone', '40mg', 'Oral', ARRAY['Chew thoroughly']),
('Lactulose', 'Gastrointestinal', 3500, 'Osmotic laxative', 'Abbott', '200ml', false, true, 4.0, 'Lactulose', '3.35g/5ml', 'Abbott Nigeria', 'Osmotic Laxative', 'Constipation', 'Lactulose', '670mg/ml', 'Oral', ARRAY['May cause flatulence initially']),
('Hyoscine Butylbromide', 'Gastrointestinal', 3200, 'Antispasmodic', 'Boehringer Ingelheim', '20 tablets', false, true, 4.3, 'Hyoscine Butylbromide', '10mg', 'Boehringer Ingelheim', 'Antispasmodic', 'Abdominal cramps', 'Scopolamine Butylbromide', '10mg', 'Oral', ARRAY['May cause drowsiness']),
('Domperidone', 'Gastrointestinal', 2800, 'Prokinetic agent', 'Janssen', '30 tablets', false, true, 4.2, 'Domperidone', '10mg', 'Janssen Nigeria', 'Dopamine Antagonist', 'Nausea, gastroparesis', 'Domperidone', '10mg', 'Oral', ARRAY['Cardiac arrhythmia risk']),

-- Mental Health & Neurology
('Fluoxetine', 'Mental Health', 4500, 'SSRI antidepressant', 'Eli Lilly', '28 capsules', true, true, 4.3, 'Fluoxetine HCl', '20mg', 'Eli Lilly Nigeria', 'SSRI', 'Depression, anxiety', 'Fluoxetine', '20mg', 'Oral', ARRAY['May take 4-6 weeks for full effect']),
('Sertraline', 'Mental Health', 5200, 'SSRI antidepressant', 'Pfizer', '30 tablets', true, true, 4.4, 'Sertraline HCl', '50mg', 'Pfizer Nigeria', 'SSRI', 'Depression, panic disorder', 'Sertraline', '50mg', 'Oral', ARRAY['Take with food']),
('Lorazepam', 'Mental Health', 3800, 'Benzodiazepine anxiolytic', 'Pfizer', '30 tablets', true, true, 4.2, 'Lorazepam', '1mg', 'Pfizer Nigeria', 'Benzodiazepine', 'Anxiety disorders', 'Lorazepam', '1mg', 'Oral', ARRAY['Risk of dependence']),
('Diazepam', 'Mental Health', 2500, 'Benzodiazepine', 'Roche', '30 tablets', true, true, 4.1, 'Diazepam', '5mg', 'Roche Nigeria', 'Benzodiazepine', 'Anxiety, muscle spasms', 'Diazepam', '5mg', 'Oral', ARRAY['Avoid alcohol']),
('Amitriptyline', 'Mental Health', 3200, 'Tricyclic antidepressant', 'Teva', '28 tablets', true, true, 4.0, 'Amitriptyline HCl', '25mg', 'Teva Nigeria', 'TCA', 'Depression, neuropathic pain', 'Amitriptyline', '25mg', 'Oral', ARRAY['Sedating, take at night']),
('Carbamazepine', 'Mental Health', 4800, 'Mood stabilizer and anticonvulsant', 'Novartis', '50 tablets', true, true, 4.2, 'Carbamazepine', '200mg', 'Novartis Nigeria', 'Anticonvulsant', 'Epilepsy, bipolar disorder', 'Carbamazepine', '200mg', 'Oral', ARRAY['Monitor blood levels']),
('Phenytoin', 'Mental Health', 2800, 'Anticonvulsant', 'Pfizer', '30 tablets', true, true, 4.1, 'Phenytoin Sodium', '100mg', 'Pfizer Nigeria', 'Anticonvulsant', 'Epilepsy', 'Phenytoin', '100mg', 'Oral', ARRAY['Gum hyperplasia risk']),
('Valproic Acid', 'Mental Health', 5500, 'Anticonvulsant and mood stabilizer', 'Abbott', '30 tablets', true, true, 4.3, 'Valproic Acid', '500mg', 'Abbott Nigeria', 'Anticonvulsant', 'Epilepsy, bipolar disorder', 'Valproic Acid', '500mg', 'Oral', ARRAY['Liver function monitoring']),
('Haloperidol', 'Mental Health', 3500, 'Typical antipsychotic', 'Janssen', '30 tablets', true, true, 3.9, 'Haloperidol', '5mg', 'Janssen Nigeria', 'Typical Antipsychotic', 'Schizophrenia, psychosis', 'Haloperidol', '5mg', 'Oral', ARRAY['Extrapyramidal side effects']),
('Risperidone', 'Mental Health', 8500, 'Atypical antipsychotic', 'Janssen', '30 tablets', true, true, 4.2, 'Risperidone', '2mg', 'Janssen Nigeria', 'Atypical Antipsychotic', 'Schizophrenia, bipolar mania', 'Risperidone', '2mg', 'Oral', ARRAY['Weight gain risk']),

-- Vitamins & Supplements
('Multivitamin Complex', 'Supplements', 4500, 'Complete daily vitamin supplement', 'Centrum', '60 tablets', false, true, 4.6, 'Multiple Vitamins', 'Various', 'Pfizer', 'Vitamin Supplement', 'Nutritional support', 'Multivitamin', 'Various', 'Oral', ARRAY['Take with food']),
('Vitamin D3', 'Supplements', 3200, 'High-potency vitamin D supplement', 'Vigantol', '30 tablets', false, true, 4.5, 'Cholecalciferol', '1000 IU', 'Merck', 'Vitamin Supplement', 'Bone health', 'Vitamin D3', '1000 IU', 'Oral', ARRAY['Take with fatty meal']),
('Calcium + Magnesium', 'Supplements', 3800, 'Bone health supplement', 'Caltrate', '60 tablets', false, true, 4.4, 'Calcium Carbonate, Magnesium', '600mg/400mg', 'Pfizer', 'Mineral Supplement', 'Bone strength', 'Calcium/Magnesium', '600mg/400mg', 'Oral', ARRAY['Take between meals']),
('Omega-3 Fish Oil', 'Supplements', 5500, 'EPA/DHA for heart and brain health', 'Seven Seas', '60 capsules', false, true, 4.7, 'EPA/DHA', '1000mg', 'Seven Seas', 'Omega-3 Supplement', 'Cardiovascular health', 'Fish Oil', '1000mg', 'Oral', ARRAY['Store in refrigerator']),
('Folic Acid', 'Supplements', 1500, 'Essential for pregnancy and fertility', 'Folacin', '30 tablets', false, true, 4.7, 'Folic Acid', '5mg', 'Various', 'Vitamin', 'Pregnancy support', 'Folic Acid', '5mg', 'Oral', ARRAY['Take before conception']),
('Iron + Vitamin C', 'Supplements', 2800, 'Iron supplement with enhanced absorption', 'Feroglobin', '30 capsules', false, true, 4.4, 'Ferrous Fumarate, Vitamin C', '305mg/70mg', 'Vitabiotics', 'Iron Supplement', 'Iron deficiency anemia', 'Iron/Vitamin C', '305mg/70mg', 'Oral', ARRAY['May cause stomach upset']),
('Vitamin B Complex', 'Supplements', 3500, 'Complete B vitamin formula', 'Neurobion', '30 tablets', false, true, 4.3, 'B Vitamins Complex', 'Various', 'Merck', 'Vitamin Supplement', 'Nerve function', 'B Complex', 'Various', 'Oral', ARRAY['Take in morning']),
('Zinc Tablets', 'Supplements', 2200, 'Essential mineral supplement', 'Zinc-C', '30 tablets', false, true, 4.2, 'Zinc Sulfate', '20mg', 'Nature''s Bounty', 'Mineral Supplement', 'Immune support', 'Zinc', '20mg', 'Oral', ARRAY['Take on empty stomach']),
('Vitamin C', 'Supplements', 1800, 'Immune system support', 'Redoxon', '30 tablets', false, true, 4.5, 'Ascorbic Acid', '500mg', 'Bayer', 'Vitamin Supplement', 'Immune support', 'Vitamin C', '500mg', 'Oral', ARRAY['May cause stomach upset in large doses']),
('Cod Liver Oil', 'Supplements', 4200, 'Vitamins A and D supplement', 'Seven Seas', '60 capsules', false, true, 4.1, 'Vitamin A, Vitamin D', '800IU/400IU', 'Seven Seas', 'Vitamin Supplement', 'Bone and vision health', 'Cod Liver Oil', '800IU/400IU', 'Oral', ARRAY['Do not exceed recommended dose']),

-- Antifungal & Antimalarial
('Fluconazole', 'Antifungal', 3800, 'Systemic antifungal', 'Pfizer', '7 capsules', true, true, 4.5, 'Fluconazole', '150mg', 'Pfizer Nigeria', 'Triazole Antifungal', 'Candidiasis, cryptococcal meningitis', 'Fluconazole', '150mg', 'Oral', ARRAY['Monitor liver function']),
('Clotrimazole Cream', 'Antifungal', 2500, 'Topical antifungal', 'Bayer', '30g tube', false, true, 4.3, 'Clotrimazole', '1%', 'Bayer Nigeria', 'Topical Antifungal', 'Skin fungal infections', 'Clotrimazole', '1%', 'Topical', ARRAY['Apply to clean, dry skin']),
('Ketoconazole Shampoo', 'Antifungal', 3500, 'Antifungal shampoo', 'Nizoral', '200ml', false, true, 4.4, 'Ketoconazole', '2%', 'Janssen', 'Topical Antifungal', 'Dandruff, seborrheic dermatitis', 'Ketoconazole', '2%', 'Topical', ARRAY['Use twice weekly']),
('Artemether-Lumefantrine', 'Antimalarial', 2800, 'ACT for malaria treatment', 'Coartem', '24 tablets', true, true, 4.6, 'Artemether/Lumefantrine', '20mg/120mg', 'Novartis', 'Antimalarial', 'Uncomplicated malaria', 'Artemether/Lumefantrine', '20mg/120mg', 'Oral', ARRAY['Take with fatty food']),
('Chloroquine', 'Antimalarial', 1500, 'Traditional antimalarial', 'Emzor', '20 tablets', true, true, 4.0, 'Chloroquine Phosphate', '250mg', 'Emzor Pharmaceuticals', 'Antimalarial', 'Malaria prophylaxis', 'Chloroquine', '250mg', 'Oral', ARRAY['Resistance common']),
('Artesunate Injection', 'Antimalarial', 8500, 'Severe malaria treatment', 'Guilin', '1 vial', true, true, 4.8, 'Artesunate', '60mg', 'Guilin Pharmaceutical', 'Antimalarial', 'Severe malaria', 'Artesunate', '60mg', 'Injection', ARRAY['Hospital use only']),
('Mefloquine', 'Antimalarial', 4500, 'Malaria prophylaxis', 'Lariam', '8 tablets', true, true, 4.1, 'Mefloquine HCl', '250mg', 'Roche', 'Antimalarial', 'Malaria prevention', 'Mefloquine', '250mg', 'Oral', ARRAY['Neuropsychiatric effects']),
('Proguanil', 'Antimalarial', 3200, 'Malaria prophylaxis', 'Paludrine', '28 tablets', true, true, 4.2, 'Proguanil HCl', '100mg', 'AstraZeneca', 'Antimalarial', 'Malaria prevention', 'Proguanil', '100mg', 'Oral', ARRAY['Take with food']),
('Sulfadoxine-Pyrimethamine', 'Antimalarial', 1800, 'Intermittent preventive treatment', 'Fansidar', '3 tablets', true, true, 4.3, 'Sulfadoxine/Pyrimethamine', '500mg/25mg', 'Roche', 'Antimalarial', 'Malaria treatment', 'SP', '500mg/25mg', 'Oral', ARRAY['Single dose treatment']),
('Quinine Tablets', 'Antimalarial', 2200, 'Traditional antimalarial', 'Quinine', '30 tablets', true, true, 3.9, 'Quinine Sulfate', '300mg', 'Various', 'Antimalarial', 'Complicated malaria', 'Quinine', '300mg', 'Oral', ARRAY['Monitor for cinchonism']);
