
-- Insert comprehensive Nigerian medications (Part 3 of 5)
INSERT INTO public.medications (
  name, category, price, description, brand, pack_size, prescription_required, 
  in_stock, rating, active_ingredient, dosage, manufacturer, therapeutic_class, 
  indication, generic_name, strength, route_of_administration, warnings
) VALUES

-- Skin Care & Dermatology
('Hydrocortisone Cream', 'Skin Care', 2200, 'Mild topical steroid', 'GSK', '30g tube', false, true, 4.4, 'Hydrocortisone', '1%', 'GSK Nigeria', 'Topical Corticosteroid', 'Eczema, dermatitis', 'Hydrocortisone', '1%', 'Topical', ARRAY['Do not use on face for more than 5 days']),
('Betamethasone Cream', 'Skin Care', 3500, 'Potent topical steroid', 'GSK', '30g tube', true, true, 4.3, 'Betamethasone Valerate', '0.1%', 'GSK Nigeria', 'Topical Corticosteroid', 'Severe eczema, psoriasis', 'Betamethasone', '0.1%', 'Topical', ARRAY['Avoid prolonged use']),
('Calamine Lotion', 'Skin Care', 1200, 'Soothing anti-itch lotion', 'Emzor', '100ml', false, true, 4.2, 'Calamine, Zinc Oxide', '15%/5%', 'Emzor Pharmaceuticals', 'Topical Antipruritic', 'Itching, minor skin irritation', 'Calamine', '15%', 'Topical', ARRAY['Shake well before use']),
('Tretinoin Cream', 'Skin Care', 4800, 'Retinoid for acne treatment', 'Johnson & Johnson', '20g tube', true, true, 4.5, 'Tretinoin', '0.025%', 'Johnson & Johnson', 'Topical Retinoid', 'Acne vulgaris', 'Tretinoin', '0.025%', 'Topical', ARRAY['Use sunscreen, avoid pregnancy']),
('Benzoyl Peroxide Gel', 'Skin Care', 3200, 'Antibacterial acne treatment', 'Galderma', '40g tube', false, true, 4.3, 'Benzoyl Peroxide', '5%', 'Galderma', 'Topical Antibacterial', 'Acne vulgaris', 'Benzoyl Peroxide', '5%', 'Topical', ARRAY['May bleach fabrics']),
('Petroleum Jelly', 'Skin Care', 800, 'Protective skin barrier', 'Vaseline', '100g jar', false, true, 4.6, 'Petrolatum', '100%', 'Unilever', 'Skin Protectant', 'Dry skin, minor cuts', 'Petrolatum', '100%', 'Topical', ARRAY['External use only']),
('Zinc Oxide Cream', 'Skin Care', 1500, 'Protective barrier cream', 'Sudocrem', '60g tube', false, true, 4.5, 'Zinc Oxide', '15.25%', 'Teva', 'Skin Protectant', 'Diaper rash, minor wounds', 'Zinc Oxide', '15.25%', 'Topical', ARRAY['Apply thin layer']),
('Salicylic Acid Solution', 'Skin Care', 2800, 'Keratolytic for warts', 'DuoFilm', '15ml', false, true, 4.1, 'Salicylic Acid', '16.7%', 'Stiefel', 'Keratolytic', 'Warts, calluses', 'Salicylic Acid', '16.7%', 'Topical', ARRAY['Avoid healthy skin']),
('Mupirocin Ointment', 'Skin Care', 4200, 'Topical antibiotic', 'GSK', '15g tube', true, true, 4.4, 'Mupirocin', '2%', 'GSK Nigeria', 'Topical Antibiotic', 'Bacterial skin infections', 'Mupirocin', '2%', 'Topical', ARRAY['Complete treatment course']),
('Fusidic Acid Cream', 'Skin Care', 3800, 'Topical antibiotic', 'Leo Pharma', '15g tube', true, true, 4.2, 'Fusidic Acid', '2%', 'Leo Pharma', 'Topical Antibiotic', 'Bacterial skin infections', 'Fusidic Acid', '2%', 'Topical', ARRAY['Apply three times daily']),

-- Eye & Ear Medications
('Chloramphenicol Eye Drops', 'Ophthalmology', 2500, 'Antibiotic eye drops', 'Allergan', '10ml', true, true, 4.5, 'Chloramphenicol', '0.5%', 'Allergan', 'Ophthalmic Antibiotic', 'Bacterial conjunctivitis', 'Chloramphenicol', '0.5%', 'Ophthalmic', ARRAY['Complete treatment course']),
('Artificial Tears', 'Ophthalmology', 1800, 'Lubricating eye drops', 'Refresh', '15ml', false, true, 4.3, 'Carboxymethylcellulose', '0.5%', 'Allergan', 'Ocular Lubricant', 'Dry eyes', 'CMC', '0.5%', 'Ophthalmic', ARRAY['Discard 28 days after opening']),
('Prednisolone Eye Drops', 'Ophthalmology', 3500, 'Anti-inflammatory eye drops', 'Allergan', '5ml', true, true, 4.4, 'Prednisolone Acetate', '1%', 'Allergan', 'Ophthalmic Corticosteroid', 'Eye inflammation', 'Prednisolone', '1%', 'Ophthalmic', ARRAY['Monitor intraocular pressure']),
('Timolol Eye Drops', 'Ophthalmology', 4800, 'Glaucoma treatment', 'Merck', '5ml', true, true, 4.2, 'Timolol Maleate', '0.5%', 'Merck', 'Beta-blocker', 'Glaucoma, ocular hypertension', 'Timolol', '0.5%', 'Ophthalmic', ARRAY['Monitor heart rate']),
('Tropicamide Eye Drops', 'Ophthalmology', 3200, 'Mydriatic for eye exams', 'Bausch & Lomb', '15ml', true, true, 4.1, 'Tropicamide', '1%', 'Bausch & Lomb', 'Mydriatic', 'Pupil dilation', 'Tropicamide', '1%', 'Ophthalmic', ARRAY['Temporary blurred vision']),
('Ciprofloxacin Ear Drops', 'ENT', 3800, 'Antibiotic ear drops', 'Alcon', '5ml', true, true, 4.3, 'Ciprofloxacin', '0.3%', 'Alcon', 'Otic Antibiotic', 'Bacterial otitis externa', 'Ciprofloxacin', '0.3%', 'Otic', ARRAY['Warm to body temperature before use']),
('Wax Removal Drops', 'ENT', 1500, 'Cerumen removal aid', 'Waxsol', '10ml', false, true, 4.0, 'Docusate Sodium', '0.5%', 'Reckitt Benckiser', 'Cerumenolytic', 'Earwax removal', 'Docusate', '0.5%', 'Otic', ARRAY['Do not use if eardrum perforated']),
('Gentamicin Eye/Ear Drops', 'Ophthalmology', 2800, 'Aminoglycoside antibiotic', 'Alcon', '10ml', true, true, 4.2, 'Gentamicin', '0.3%', 'Alcon', 'Aminoglycoside', 'Bacterial infections', 'Gentamicin', '0.3%', 'Ophthalmic/Otic', ARRAY['Monitor for ototoxicity']),
('Cyclopentolate Eye Drops', 'Ophthalmology', 4200, 'Cycloplegic agent', 'Alcon', '15ml', true, true, 4.0, 'Cyclopentolate HCl', '1%', 'Alcon', 'Cycloplegic', 'Refraction, uveitis', 'Cyclopentolate', '1%', 'Ophthalmic', ARRAY['Photophobia expected']),
('Sodium Cromoglicate Eye Drops', 'Ophthalmology', 3500, 'Mast cell stabilizer', 'Bausch & Lomb', '10ml', false, true, 4.1, 'Sodium Cromoglicate', '2%', 'Bausch & Lomb', 'Mast Cell Stabilizer', 'Allergic conjunctivitis', 'Cromoglicate', '2%', 'Ophthalmic', ARRAY['Regular use required']),

-- Hormones & Endocrine
('Levothyroxine', 'Endocrine', 3800, 'Thyroid hormone replacement', 'Merck', '30 tablets', true, true, 4.6, 'Levothyroxine Sodium', '100mcg', 'Merck Nigeria', 'Thyroid Hormone', 'Hypothyroidism', 'T4', '100mcg', 'Oral', ARRAY['Take on empty stomach']),
('Insulin NPH', 'Diabetes', 8500, 'Intermediate-acting insulin', 'Novo Nordisk', '1 vial', true, true, 4.5, 'Insulin NPH', '100 units/ml', 'Novo Nordisk', 'Intermediate-acting Insulin', 'Diabetes mellitus', 'NPH Insulin', '100 units/ml', 'Injection', ARRAY['Roll gently, do not shake']),
('Prednisolone Tablets', 'Endocrine', 2500, 'Systemic corticosteroid', 'GSK', '30 tablets', true, true, 4.3, 'Prednisolone', '5mg', 'GSK Nigeria', 'Corticosteroid', 'Inflammatory conditions', 'Prednisolone', '5mg', 'Oral', ARRAY['Taper dose gradually']),
('Dexamethasone Tablets', 'Endocrine', 3200, 'Potent corticosteroid', 'GSK', '30 tablets', true, true, 4.2, 'Dexamethasone', '0.5mg', 'GSK Nigeria', 'Corticosteroid', 'Severe inflammation', 'Dexamethasone', '0.5mg', 'Oral', ARRAY['Immunosuppression risk']),
('Testosterone Gel', 'Endocrine', 12500, 'Hormone replacement therapy', 'AndroGel', '30 sachets', true, true, 4.1, 'Testosterone', '50mg/sachet', 'AbbVie', 'Androgen', 'Hypogonadism', 'Testosterone', '50mg', 'Topical', ARRAY['Wash hands after application']),
('Estradiol Patches', 'Endocrine', 8500, 'Estrogen replacement therapy', 'Vivelle', '8 patches', true, true, 4.0, 'Estradiol', '0.05mg/day', 'Novartis', 'Estrogen', 'Menopause', 'Estradiol', '0.05mg/day', 'Transdermal', ARRAY['Rotate application sites']),
('Hydrocortisone Tablets', 'Endocrine', 2800, 'Corticosteroid replacement', 'Pfizer', '30 tablets', true, true, 4.2, 'Hydrocortisone', '20mg', 'Pfizer Nigeria', 'Corticosteroid', 'Adrenal insufficiency', 'Hydrocortisone', '20mg', 'Oral', ARRAY['Take with food']),
('Fludrocortisone', 'Endocrine', 4500, 'Mineralocorticoid', 'Aspen', '30 tablets', true, true, 4.1, 'Fludrocortisone Acetate', '0.1mg', 'Aspen Pharma', 'Mineralocorticoid', 'Addison''s disease', 'Fludrocortisone', '0.1mg', 'Oral', ARRAY['Monitor electrolytes']),
('Growth Hormone', 'Endocrine', 45000, 'Recombinant human growth hormone', 'Genotropin', '1 pen', true, true, 4.7, 'Somatropin', '12mg', 'Pfizer', 'Growth Hormone', 'Growth hormone deficiency', 'hGH', '12mg', 'Injection', ARRAY['Refrigerate, expensive therapy']),
('Calcitriol', 'Endocrine', 5500, 'Active vitamin D analog', 'Rocaltrol', '30 capsules', true, true, 4.3, 'Calcitriol', '0.25mcg', 'Roche', 'Vitamin D Analog', 'Hypocalcemia, osteoporosis', 'Calcitriol', '0.25mcg', 'Oral', ARRAY['Monitor calcium levels']),

-- Pediatric Formulations
('Paracetamol Suspension', 'Pediatrics', 1800, 'Pain and fever relief for children', 'Calpol', '100ml', false, true, 4.7, 'Paracetamol', '120mg/5ml', 'Johnson & Johnson', 'Pediatric Analgesic', 'Pediatric pain, fever', 'Acetaminophen', '24mg/ml', 'Oral', ARRAY['Dose by weight']),
('Ibuprofen Suspension', 'Pediatrics', 2200, 'Anti-inflammatory for children', 'Nurofen', '100ml', false, true, 4.6, 'Ibuprofen', '100mg/5ml', 'Reckitt Benckiser', 'Pediatric NSAID', 'Pediatric pain, fever', 'Ibuprofen', '20mg/ml', 'Oral', ARRAY['Not for infants under 6 months']),
('Amoxicillin Suspension', 'Pediatrics', 3500, 'Antibiotic for children', 'GSK', '100ml', true, true, 4.5, 'Amoxicillin', '250mg/5ml', 'GSK Nigeria', 'Pediatric Antibiotic', 'Pediatric infections', 'Amoxicillin', '50mg/ml', 'Oral', ARRAY['Refrigerate after reconstitution']),
('ORS for Children', 'Pediatrics', 650, 'Pediatric rehydration salts', 'WHO', '10 sachets', false, true, 4.8, 'Glucose, Electrolytes', 'Low osmolarity', 'WHO/UNICEF', 'Pediatric Rehydration', 'Pediatric dehydration', 'Pediatric ORS', 'Low osmolarity', 'Oral', ARRAY['Use correct dilution']),
('Vitamin Drops', 'Pediatrics', 2800, 'Multivitamin drops for infants', 'Abidec', '25ml', false, true, 4.4, 'Multiple Vitamins', 'Various', 'Pfizer', 'Pediatric Vitamins', 'Nutritional support', 'Infant Vitamins', 'Various', 'Oral', ARRAY['Do not exceed recommended dose']),
('Iron Drops', 'Pediatrics', 2200, 'Iron supplement for children', 'Feroglobin B12', '30ml', false, true, 4.3, 'Ferrous Gluconate', '25mg/ml', 'Vitabiotics', 'Pediatric Iron', 'Iron deficiency', 'Iron', '25mg/ml', 'Oral', ARRAY['May stain teeth, use dropper']),
('Gripe Water', 'Pediatrics', 1500, 'Colic relief for infants', 'Woodward''s', '150ml', false, true, 4.2, 'Dill Oil, Sodium Bicarbonate', 'Various', 'Woodward''s', 'Infant Digestive Aid', 'Infant colic', 'Gripe Water', 'Various', 'Oral', ARRAY['Traditional remedy']),
('Teething Gel', 'Pediatrics', 1800, 'Teething pain relief', 'Bonjela', '15g', false, true, 4.1, 'Choline Salicylate', '8.7%', 'Reckitt Benckiser', 'Topical Analgesic', 'Teething pain', 'Choline Salicylate', '8.7%', 'Topical', ARRAY['Use sparingly']),
('Infant Paracetamol Suppositories', 'Pediatrics', 2500, 'Fever relief for infants', 'Tylenol', '10 suppositories', false, true, 4.3, 'Paracetamol', '80mg', 'Johnson & Johnson', 'Pediatric Analgesic', 'Infant fever', 'Acetaminophen', '80mg', 'Rectal', ARRAY['Alternative when oral not possible']),
('Zinc Oral Solution', 'Pediatrics', 1200, 'Zinc supplement for children', 'Zinplex', '100ml', false, true, 4.2, 'Zinc Sulfate', '5mg/5ml', 'Aspen Pharma', 'Pediatric Mineral', 'Diarrhea management', 'Zinc', '1mg/ml', 'Oral', ARRAY['WHO recommended for diarrhea']),

-- Contraceptives & Sexual Health
('Combined Oral Contraceptive', 'Contraceptives', 2800, 'Birth control pills', 'Yasmin', '21 tablets', true, true, 4.5, 'Ethinylestradiol/Drospirenone', '0.03mg/3mg', 'Bayer', 'Contraceptive', 'Pregnancy prevention', 'COC', '0.03mg/3mg', 'Oral', ARRAY['Take at same time daily']),
('Progesterone-only Pill', 'Contraceptives', 2200, 'Mini-pill contraceptive', 'Micronor', '28 tablets', true, true, 4.3, 'Norethisterone', '0.35mg', 'Janssen', 'Contraceptive', 'Pregnancy prevention', 'POP', '0.35mg', 'Oral', ARRAY['Very strict timing required']),
('Emergency Contraceptive', 'Contraceptives', 3500, 'Morning-after pill', 'Postinor', '1 tablet', false, true, 4.4, 'Levonorgestrel', '1.5mg', 'Gedeon Richter', 'Emergency Contraceptive', 'Emergency contraception', 'Plan B', '1.5mg', 'Oral', ARRAY['Use within 72 hours']),
('Male Condoms', 'Contraceptives', 1200, 'Barrier contraception', 'Durex', '12 pieces', false, true, 4.6, 'Latex', 'Standard', 'Reckitt Benckiser', 'Barrier Contraceptive', 'Pregnancy and STI prevention', 'Condoms', 'Standard', 'External', ARRAY['Check expiry date']),
('Female Condoms', 'Contraceptives', 2500, 'Female barrier method', 'Femidom', '3 pieces', false, true, 4.2, 'Polyurethane', 'Standard', 'Female Health Company', 'Barrier Contraceptive', 'Pregnancy and STI prevention', 'Female Condoms', 'Standard', 'Internal', ARRAY['Single use only']),
('Spermicidal Gel', 'Contraceptives', 1800, 'Contraceptive gel', 'Gynol II', '81g', false, true, 4.0, 'Nonoxynol-9', '2%', 'Advanced Care Products', 'Spermicide', 'Additional contraceptive protection', 'N-9', '2%', 'Vaginal', ARRAY['Use with barrier methods']),
('Sildenafil', 'Sexual Health', 8500, 'Erectile dysfunction treatment', 'Viagra', '4 tablets', true, true, 4.3, 'Sildenafil Citrate', '50mg', 'Pfizer', 'PDE5 Inhibitor', 'Erectile dysfunction', 'Sildenafil', '50mg', 'Oral', ARRAY['Avoid with nitrates']),
('Tadalafil', 'Sexual Health', 12500, 'Long-acting ED treatment', 'Cialis', '4 tablets', true, true, 4.4, 'Tadalafil', '20mg', 'Eli Lilly', 'PDE5 Inhibitor', 'Erectile dysfunction', 'Tadalafil', '20mg', 'Oral', ARRAY['Effects last up to 36 hours']),
('Dapoxetine', 'Sexual Health', 6500, 'Premature ejaculation treatment', 'Priligy', '6 tablets', true, true, 4.1, 'Dapoxetine HCl', '30mg', 'Janssen', 'SSRI', 'Premature ejaculation', 'Dapoxetine', '30mg', 'Oral', ARRAY['Take 1-3 hours before intercourse']),
('Clomiphene', 'Sexual Health', 4800, 'Fertility treatment', 'Clomid', '10 tablets', true, true, 4.2, 'Clomiphene Citrate', '50mg', 'Sanofi', 'Selective Estrogen Receptor Modulator', 'Female infertility', 'Clomiphene', '50mg', 'Oral', ARRAY['Monitor ovulation']);
